### ISSUE TITLE
issue with TESTNG-Grouping

### ISSUE THREAD

**Issue by jayanaidu33** [tabhresh/Edureka_27thMay#4]
TestNG Script:

package day5;

import org.testng.annotations.Test;

public class Grouping {
  @Test(groups="Sanity")
  public void Test1() {
	  
	  System.out.println("Test1");
  }
  
  @Test(groups="Smoke")
  public void Test2() {
	  
	  System.out.println("Test2");
  }
  
  @Test(groups="Sanity")
  public void Test3() {
	  
	  System.out.println("Test3");
  }
  
  @Test(groups="Smoke")
  public void Test4() {
	  
	  System.out.println("Test4");
  }
}

TestNG.XML

<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >

<suite name="Suite" parallel="false">
  <test name="Test">
  <groups>
  <run>
  <include name="Smoke"></include>
  </run>
  groups>
    <classes>
      <class name="day5.Grouping"/>
    </classes>
  </test> 
</suite> 

Error:

[RemoteTestNG] detected TestNG version 6.14.3
org.testng.TestNGException: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.testng.TestNG.parseSuite(TestNG.java:327)
	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:348)
	at org.testng.TestNG.initializeEverything(TestNG.java:995)
	at org.testng.remote.support.RemoteTestNG6_12.initialize(RemoteTestNG6_12.java:22)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:98)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.security.cert.CertPathBuilder.build(Unknown Source)
	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at sun.security.validator.Validator.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	at org.apache.xerces.impl.XMLEntityManager.startEntity(Unknown Source)
	at org.apache.xerces.impl.XMLEntityManager.startDTDEntity(Unknown Source)
	at org.apache.xerces.impl.XMLDTDScannerImpl.setInputSource(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentScannerImpl$DTDDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(Unknown Source)
	at org.testng.xml.XMLParser.parse(XMLParser.java:38)
	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:16)
	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:9)
	at org.testng.xml.Parser.parse(Parser.java:152)
	at org.testng.xml.Parser.parse(Parser.java:233)
	at org.testng.TestNG.parseSuite(TestNG.java:295)

**Comment by AbhreshSugandhi** [comment]
where is ur XML file?

**Comment by luoyq-Rockey** [comment]
I have the same problem
`D:\SoftWare\Java\bin\java.exe -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:D:\SoftWare\IntelliJ IDEA Ultimate\lib\idea_rt.jar=57296:D:\SoftWare\IntelliJ IDEA Ultimate\bin" -Dfile.encoding=UTF-8 -classpath "D:\SoftWare\IntelliJ IDEA Ultimate\lib\idea_rt.jar;D:\SoftWare\IntelliJ IDEA Ultimate\plugins\testng\lib\testng-rt.jar;D:\SoftWare\Java\jre\lib\charsets.jar;D:\SoftWare\Java\jre\lib\deploy.jar;D:\SoftWare\Java\jre\lib\ext\access-bridge-32.jar;D:\SoftWare\Java\jre\lib\ext\cldrdata.jar;D:\SoftWare\Java\jre\lib\ext\dnsns.jar;D:\SoftWare\Java\jre\lib\ext\jaccess.jar;D:\SoftWare\Java\jre\lib\ext\jfxrt.jar;D:\SoftWare\Java\jre\lib\ext\localedata.jar;D:\SoftWare\Java\jre\lib\ext\nashorn.jar;D:\SoftWare\Java\jre\lib\ext\sunec.jar;D:\SoftWare\Java\jre\lib\ext\sunjce_provider.jar;D:\SoftWare\Java\jre\lib\ext\sunmscapi.jar;D:\SoftWare\Java\jre\lib\ext\sunpkcs11.jar;D:\SoftWare\Java\jre\lib\ext\zipfs.jar;D:\SoftWare\Java\jre\lib\javaws.jar;D:\SoftWare\Java\jre\lib\jce.jar;D:\SoftWare\Java\jre\lib\jfr.jar;D:\SoftWare\Java\jre\lib\jfxswt.jar;D:\SoftWare\Java\jre\lib\jsse.jar;D:\SoftWare\Java\jre\lib\management-agent.jar;D:\SoftWare\Java\jre\lib\plugin.jar;D:\SoftWare\Java\jre\lib\resources.jar;D:\SoftWare\Java\jre\lib\rt.jar;D:\AiIneterfaceTest\inc-aiplat-core-test\target\test-classes;D:\AiIneterfaceTest\inc-aiplat-core-test\target\classes;D:\tools\apache-maven-3.5.4-bin\m2\junit\junit\4.12\junit-4.12.jar;D:\tools\apache-maven-3.5.4-bin\m2\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;D:\tools\apache-maven-3.5.4-bin\m2\org\testng\testng\6.14.3\testng-6.14.3.jar;D:\tools\apache-maven-3.5.4-bin\m2\com\beust\jcommander\1.72\jcommander-1.72.jar;D:\tools\apache-maven-3.5.4-bin\m2\org\apache-extras\beanshell\bsh\2.0b6\bsh-2.0b6.jar;D:\tools\apache-maven-3.5.4-bin\m2\io\qameta\allure\allure-testng\2.25.0\allure-testng-2.25.0.jar;D:\tools\apache-maven-3.5.4-bin\m2\io\qameta\allure\allure-java-commons\2.25.0\allure-java-commons-2.25.0.jar;D:\tools\apache-maven-3.5.4-bin\m2\org\slf4j\slf4j-api\1.7.36\slf4j-api-1.7.36.jar;D:\tools\apache-maven-3.5.4-bin\m2\io\qameta\allure\allure-model\2.25.0\allure-model-2.25.0.jar;D:\tools\apache-maven-3.5.4-bin\m2\io\qameta\allure\allure-test-filter\2.25.0\allure-test-filter-2.25.0.jar;D:\tools\apache-maven-3.5.4-bin\m2\com\alibaba\fastjson\1.2.78\fastjson-1.2.78.jar;D:\tools\apache-maven-3.5.4-bin\m2\cn\hutool\hutool-all\5.8.26\hutool-all-5.8.26.jar;D:\tools\apache-maven-3.5.4-bin\m2\org\jsoup\jsoup\1.15.3\jsoup-1.15.3.jar;D:\tools\apache-maven-3.5.4-bin\m2\org\junit\jupiter\junit-jupiter\5.10.2\junit-jupiter-5.10.2.jar;D:\tools\apache-maven-3.5.4-bin\m2\org\junit\jupiter\junit-jupiter-api\5.10.2\junit-jupiter-api-5.10.2.jar;D:\tools\apache-maven-3.5.4-bin\m2\org\opentest4j\opentest4j\1.3.0\opentest4j-1.3.0.jar;D:\tools\apache-maven-3.5.4-bin\m2\org\junit\platform\junit-platform-commons\1.10.2\junit-platform-commons-1.10.2.jar;D:\tools\apache-maven-3.5.4-bin\m2\org\apiguardian\apiguardian-api\1.1.2\apiguardian-api-1.1.2.jar;D:\tools\apache-maven-3.5.4-bin\m2\org\junit\jupiter\junit-jupiter-params\5.10.2\junit-jupiter-params-5.10.2.jar;D:\tools\apache-maven-3.5.4-bin\m2\org\junit\jupiter\junit-jupiter-engine\5.10.2\junit-jupiter-engine-5.10.2.jar;D:\tools\apache-maven-3.5.4-bin\m2\org\junit\platform\junit-platform-engine\1.10.2\junit-platform-engine-1.10.2.jar" com.intellij.rt.testng.RemoteTestNGStarter -usedefaultlisteners false -socket57295 @w@C:\Users\01416279\AppData\Local\Temp\idea_working_dirs_testng.tmp -temp C:\Users\01416279\AppData\Local\Temp\idea_testng.tmp
org.testng.TestNGException: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.testng.TestNG.parseSuite(TestNG.java:327)
	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:348)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:39)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:647)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1305)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:1271)
	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:263)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1167)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1050)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:964)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at org.testng.xml.XMLParser.parse(XMLParser.java:38)
	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:16)
	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:9)
	at org.testng.xml.Parser.parse(Parser.java:152)
	at org.testng.xml.Parser.parse(Parser.java:233)
	at org.testng.TestNG.parseSuite(TestNG.java:295)`

**Comment by luoyq-Rockey** [comment]
I have the same problem and I don't know how to solve it, but if I run it directly using TestNG.xml, won't this problem occur
If I am alone in my case class run one of the cases, can appear org. Testng. TestNGException: sun. Security. The provider. Certpath. SunCertPathBuilderException: unable to find valid certification path to requested target
